// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhoklDE0nBnocblvFIeTqfU6GoldCod4',
    appId: '1:95477099575:web:deade45e0e51a9e2b823b2',
    messagingSenderId: '95477099575',
    projectId: 'store-ebecf',
    authDomain: 'store-ebecf.firebaseapp.com',
    storageBucket: 'store-ebecf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH06x4Mhld6sz3o8kIdbySUs3rsxobUN4',
    appId: '1:95477099575:android:5de6e3cc2adfdc74b823b2',
    messagingSenderId: '95477099575',
    projectId: 'store-ebecf',
    storageBucket: 'store-ebecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZwKXQahCDtNY3a7x0OJjaZw5wmh5bdc',
    appId: '1:95477099575:ios:cdd1f719b3dc325fb823b2',
    messagingSenderId: '95477099575',
    projectId: 'store-ebecf',
    storageBucket: 'store-ebecf.firebasestorage.app',
    iosBundleId: 'com.example.storeApp2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZwKXQahCDtNY3a7x0OJjaZw5wmh5bdc',
    appId: '1:95477099575:ios:cdd1f719b3dc325fb823b2',
    messagingSenderId: '95477099575',
    projectId: 'store-ebecf',
    storageBucket: 'store-ebecf.firebasestorage.app',
    iosBundleId: 'com.example.storeApp2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhoklDE0nBnocblvFIeTqfU6GoldCod4',
    appId: '1:95477099575:web:5612cd5e9b213b0ab823b2',
    messagingSenderId: '95477099575',
    projectId: 'store-ebecf',
    authDomain: 'store-ebecf.firebaseapp.com',
    storageBucket: 'store-ebecf.firebasestorage.app',
  );
}
